apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-viniciusoliveira
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-viniciusoliveira
  template:
    metadata:
      labels:
        app: frontend-viniciusoliveira
    spec:
      containers:
      - name: frontend
        image: quay.io/viniciusr01/frontend-tp2-vinicius:0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 52061