apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: project2-pv2-viniciusoliveira
spec:
 accessModes:
   - ReadWriteMany
 storageClassName: standard
 resources:
   requests:
     storage: 1Gi
 volumeName: project2-pv2