apiVersion: v1
kind: Service
metadata:
  name: playlist-recommender-viniciusoliveira-service
spec:
  selector:
    app: playlist-recommender-viniciusoliveira
  ports:
    - protocol: TCP
      port: 52061
      targetPort: 52061